apiVersion: v1
data:
  GOOGLE_API_KEY: {{ .Values.GOOGLE_API_KEY | b64enc }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: solargeometry
type: Opaque
